version: 0.0
os: linux
files:
  - source: /test.php
    destination: /usr/share/nginx/html/
hooks:
  # ApplicationStop:
  #   - location: scripts/stop_server
  #     timeout: 300
  #     runas: root
  AfterInstall:
    # - location: scripts/install_dependencies
    #   timeout: 300
    #   runas: root
    - location: scripts/start_server
      timeout: 60
      runas: root

